newsfeed_portal/newsfeed_portal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from portal.views import *
from portal.forms import EmailValidationOnForgotPassword
from django.conf.urls.static import static
from django.conf import settings

# REST
from rest_framework import routers


router = routers.DefaultRouter()

urlpatterns = [
    path(
        "userReadListTrack",
        UserReadListTrackAPIView.as_view(),
        name="userReadListTrack",
    ),
    path(
        "subscribeUpdate",
        SubscribeUpdateAPIView.as_view(),
        name="subscribeUpdate",
    ),
    path(
        "newsLetterUpdate",
        NewsLetterUpdateAPIView.as_view(),
        name="newsLetterUpdate",
    ),
    path(
        "readListDelete",
        ReadListDeleteAPIView.as_view(),
        name="readListDelete",
    ),
    # NewsLetterAPIView
    path("admin/", admin.site.urls),
    path("", include("portal.urls", namespace="portal")),
    path(
        "login/", UserLoginView.as_view(template_name="users/login.html"), name="login"
    ),
    path("signup/", UserSignUpView.as_view(), name="signup"),
    path("activate/<uidb64>/<token>/", ActivateAccount.as_view(), name="activate"),
    path(
        "password-reset/",
        MyPasswordRestView.as_view(form_class=EmailValidationOnForgotPassword),
        name="password_reset",
    ),
    path(
        "password-reset/done",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("", global_home, name="global_home"),
    path("next", loadcontent, name="Loadcontent"),
    path("routers/", include(router.urls)),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newsfeed_portal/portal/urls.py
from django.urls import path
from .views import *

app_name = "portal"

urlpatterns = [
    path("user-home/", user_home, name="user_home"),
    path("user-profile-settings/", user_profile_settings, name="user_profile_settings"),
    path(
        "create-readlist/",
        user_create_readlist,
        name="user_create_readlist",
    ),
    path(
        "manage-readlist/",
        ManageReadListsView.as_view(),
        name="user_manage_readlists",
    ),
    path(
        "top-headlines/<pk>",
        user_top_headlines,
        name="user_top_headlines",
    ),
    path(
        "full-stories/<pk>",
        user_full_stories,
        name="user_full_stories",
    ),
]

newsfeed_portal/portal/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.template.defaultfilters import slugify
from django.utils import timezone
from django.utils import timezone as tz


class User(AbstractUser):
    subscribe = models.BooleanField(
        default=False,
        help_text="This will enlist you to newsletter feature. You will get newsletter emails on latest news updates(within every 15 minutes). To stop getting news please set this field unchecked",
    )
    created_at = models.DateTimeField(auto_now_add=True)


class ReadList(models.Model):

    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=100)
    country = models.CharField(
        max_length=50, null=True, blank=True
    )  # ForeignKey(Country, on_delete=models.SET_NULL, null=True)
    source = models.CharField(
        max_length=50, null=True, blank=True
    )  # ForeignKey(Source, on_delete=models.SET_NULL, null=True)

    top_headlines_url = models.URLField()
    full_stories_url = models.URLField()

    newsletter = models.BooleanField(
        default=False,
        help_text="Checking this box will send you newsletters to your email id about the latest news updates(within every 15 minutes) based on this readlist. To stop getting news please set this field unchecked",
    )
    created_at = models.DateTimeField(default=tz.now)

    slug = models.SlugField(max_length=40)

    def __str__(self):
        return str(self.keyword)

    def slug(self):
        return slugify(self.keyword)

    class Meta:
        verbose_name = "ReadList"
        verbose_name_plural = "ReadLists"


class ReadListNewsBody(models.Model):
    readlist = models.ForeignKey(ReadList, on_delete=models.CASCADE)
    headline = models.CharField(max_length=200, unique=True)
    thumbnail = models.URLField()
    source_of_news = models.CharField(max_length=100, null=True, blank=True)
    country_of_news = models.CharField(max_length=100, null=True, blank=True)
    original_news_source_link = models.URLField()
    published_at = models.DateTimeField(default=tz.now)

    slug = models.SlugField(max_length=40)

    def __str__(self):
        return str(self.headline)

    def slug(self):
        return slugify(self.headline)

    class Meta:
        verbose_name = "ReadListNewsBody"
        verbose_name_plural = "ReadListNewsBodies"

newsfeed_portal/portal/views.py
import datetime

from .forms import *
from .models import *
from newsfeed_portal.settings import *
from .tokens import account_activation_token

# from .serializers import *

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import *
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings

from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.core.mail import send_mail

from django.db import transaction
from django.db.models import Q
from django.db.models import Count, Value, F, Sum
from django.db.models.functions import Concat

from django.http import FileResponse, JsonResponse, HttpResponse

from django.shortcuts import render, get_object_or_404, redirect

from django.template import RequestContext
from django.template.loader import render_to_string

from django.utils.decorators import method_decorator
from django.utils.encoding import force_bytes, force_text
from django.utils.http import is_safe_url
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.urls import reverse_lazy, reverse

from django.views.generic import *
from django.views.generic.detail import *

# ------------------------------------------REST-framework-----------------------------------------
from rest_framework import viewsets, permissions, filters
from rest_framework.generics import RetrieveUpdateAPIView, DestroyAPIView
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAuthenticated

import hashlib  # For Authentication

# ------------------------------------------NewsAPI-------------------------------------------------
from newsapi.newsapi_client import NewsApiClient
import requests
import json

temp_img = "https://images.pexels.com/photos/3225524/pexels-photo-3225524.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500"

# -------------------------------------------REST APIs, Class based View, Function based View strts from here------------------------------------


class UserReadListTrackAPIView(APIView):
    def post(self, request, *args, **kwargs):
        username = request.data.get(
            "username", None
        )  # readlist_id in the AJAX hold the readlist_id

        input_key = request.data.get("key", None)
        input_timestamp = request.data.get("timestamp", None)

        client_message = str(input_timestamp) + "newsfeed"

        generated_signature_by_client = hashlib.sha256(
            client_message.encode()
        ).hexdigest()

        event_status_code = 0

        timestamp_now = int(datetime.datetime.timestamp(datetime.datetime.now()))

        if username is not None or not username == "":
            if generated_signature_by_client == input_key:

                if (
                    timestamp_now <= int(input_timestamp) + 360000000
                ):  # Setting the sigtnature expiration time to 360000000 seconds or 100 hour. If needed, cange the expiration time as you wish

                    if not User.objects.filter(username=username).exists():
                        event_status_code = 0
                        status_message = ["User doesn't exist"]

                    else:
                        user_obj = get_object_or_404(User, username=username)
                        readlist_objs = ReadList.objects.filter(created_by=user_obj)

                        readlists = []
                        readlist_news_bodies = []

                        readlist_data = {
                            "id": "",
                            "keyword": "",
                            "source": "",
                            "country": "",
                            "top_headlines_url": "",
                            "full_stories_url": "",
                            "newsletter": "",
                            "created_at": "",
                        }

                        readlist_news_body_data = {
                            "id": "",
                            "readlist": "",
                            "headline": "",
                            "thumbnail": "",
                            "source_of_news": "",
                            "country_of_news": "",
                            "original_news_source_link": "",
                            "published_at": "",
                        }

                        for readlist_obj in readlist_objs:
                            readlist_data = {
                                "id": readlist_obj.id,
                                "keyword": readlist_obj.keyword,
                                "source": readlist_obj.source,
                                "country": readlist_obj.country,
                                "top_headlines_url": readlist_obj.top_headlines_url,
                                "full_stories_url": readlist_obj.full_stories_url,
                                "newsletter": readlist_obj.newsletter,
                                "created_at": readlist_obj.created_at,
                            }

                            # print(readlist_data)

                            readlists.append(readlist_data)

                            readlist_news_body_objs = ReadListNewsBody.objects.filter(
                                readlist=readlist_obj
                            )

                            for readlist_news_body_obj in readlist_news_body_objs:
                                readlist_news_body_data = {
                                    "id": readlist_news_body_obj.id,
                                    "keyword": readlist_news_body_obj.readlist.keyword,
                                    "headline": readlist_news_body_obj.headline,
                                    "thumbnail": readlist_news_body_obj.thumbnail,
                                    "source_of_news": readlist_news_body_obj.source_of_news,
                                    "country_of_news": readlist_news_body_obj.country_of_news,
                                    "original_news_source_link": readlist_news_body_obj.original_news_source_link,
                                    "published_at": readlist_news_body_obj.published_at,
                                }

                                readlist_news_bodies.append(readlist_news_body_data)

                        data = {
                            "username": user_obj.username,
                            "first_name": user_obj.first_name,
                            "last_name": user_obj.last_name,
                            "subscribed": user_obj.subscribe,
                            "readlists": readlists,
                            "curated_news": readlist_news_bodies,
                        }
                        event_status_code = 1
                        return Response({"status": event_status_code, "result": data})

                else:
                    event_status_code = 0
                    status_message = ["Signature Expired"]
            else:
                event_status_code = 0
                status_message = ["Authentication Failure"]
        else:
            event_status_code = 0
            status_message = ["No Readlist Id is given in the input"]

        return Response({"status": event_status_code, "result": status_message})


class SubscribeUpdateAPIView(APIView):
    def post(self, request, *args, **kwargs):
        username = request.data.get(
            "username", None
        )  # readlist_id in the AJAX hold the readlist_id

        is_active = request.data.get(
            "is_active", None
        )  # is_active in the AJAX holds the is_active

        input_key = request.data.get("key", None)
        input_timestamp = request.data.get("timestamp", None)

        client_message = str(input_timestamp) + "newsfeed"

        generated_signature_by_client = hashlib.sha256(
            client_message.encode()
        ).hexdigest()

        event_status_code = 0

        timestamp_now = int(datetime.datetime.timestamp(datetime.datetime.now()))

        if username is not None or not username == "":
            if generated_signature_by_client == input_key:

                if (
                    timestamp_now <= int(input_timestamp) + 360000000
                ):  # Setting the sigtnature expiration time to 360000000 seconds or 100 hour. If needed, cange the expiration time as you wish

                    if not User.objects.filter(username=username).exists():
                        event_status_code = 0
                        status_message = ["User doesn't exist"]

                    else:
                        user_obj = get_object_or_404(User, username=username)
                        user_obj.subscribe = is_active
                        user_obj.save()

                        event_status_code = 1
                        message = (
                            "Success !! Subscribe activation status is set to -> "
                            + is_active
                            + " for USER ID : "
                            + username
                        )
                        status_message = [message]

                else:
                    event_status_code = 0
                    status_message = ["Signature Expired"]
            else:
                event_status_code = 0
                status_message = ["Authentication Failure"]
        else:
            event_status_code = 0
            status_message = ["No Readlist Id is given in the input"]

        return Response({"status": event_status_code, "result": status_message})


class NewsLetterUpdateAPIView(APIView):
    def post(self, request, *args, **kwargs):
        readlist_id = request.data.get(
            "readlist_id", None
        )  # Here readlist in the AJAX hold the readlist_id

newsfeed_portal/portal/templates/portal/al-jazeera.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aljazera News</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>

<div class="jumbotron" style="color:black">

    <h1 style="color:black">
        This is the latest news

    </h1>

</div>


<div class="container">
    {% for new, des, i in mylist %}
    <img src="{{i}}" alt="">
    <h3>News:</h3> {{new}}
    {{value | linebreaks}}

    <h4>Description:</h4> {{des}}
    {{value | linebreaks}}



    {% endfor %}




</div>

</body>
</html>

newsfeed_portal/portal/templates/portal/home.html
{% extends "portal/base.html" %}
{% block content %}
    <div class="container-fluid content_area">
        <div class="row">
            <div class="col-sm-12" style="margin-bottom: 15px;">
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered nowrap">
                        <thead>
                            <tr>
                                <!-- <th>Select</th> -->
                                <th> Heading </th>
                                <th> Thumbnails </th>
                                <th> Country </th>
                                <th> Source </th>

                            </tr>
                        </thead>
                        <tbody>
                            {% for news in news_list %}
                                <tr>
                                    <td>{{ news.header }}</td>
                                    <td>{{ news.thumbnails }}</td>
                                    <td>{{ news.country }}</td>
                                    <td>{{ news.source }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                {% if is_paginated %}
                        {% if page_obj.has_previous %}
                            <a class="btn btn-outline-dark mb-4" href="?page=1 {% if q %} &q={{ q }} {% endif %}">First</a>
                            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.previous_page_number }}{% if q %} &q={{ q }} {% endif %}">Previous</a>
                        {% endif %}

                        {% for num in page_obj.paginator.page_range %}
                            {% if page_obj.number == num %}
                                <a class="btn btn-dark mb-4" href="?page={{ num }}{% if q %} &q={{ q }} {% endif %}">{{ num }}</a>
                            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <a class="btn btn-outline-dark mb-4" href="?&page={{ num }}{% if q %} &q={{ q }} {% endif %}">{{ num }}</a>
                            {% endif %}
                        {% endfor %}

                        {% if page_obj.has_next %}
                            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.next_page_number }}{% if q %} &q={{ q }} {% endif %}">Next</a>
                            <a class="btn btn-outline-dark mb-4" href="?page={{ page_obj.paginator.num_pages }}{% if q %} &q={{ q }} {% endif %}">Last</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
        <!--End Dashboard Content-->
    </div>
    <!-- End container-fluid-->
<!-- modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"> Selected Image</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <img src="" alt="Content Title" style="display:none;width:100%;" id="preview_img">
      </div>
  </div>
</div>
</div>

<!-- modal -->
<!--End content-wrapper-->
{% endblock %}

newsfeed_portal/portal/templates/portal/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>NewsFeed</title>

    <!--FAVICONS -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'portal/assets/img/bless_favicon.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'portal/assets/img/bless_favicon.png' %}">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'portal/assets/css/dataTables.bootstrap4.min.css' %}" />
    <link rel="stylesheet" href="{% static 'portal/assets/css/custom.css' %}" />

    <!-- Jquery Js  version: 3.3.1-->
    <script src="{% static 'portal/assets/js/jquery.min.js' %}"></script>
</head>

<body>
    <div class='full_page_loading_msg text-success' style="display: none;">
        <span>Processing</span>
        <i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"></i>
    </div>
    <!-- Start wrapper-->
    <div id="wrapper">

        <!--Start sidebar-wrapper-->
        <div id="sidebar-wrapper" data-simplebar=" " data-simplebar-auto-hide=" true ">
            <div class="brand-logo">
                <a href="{% url 'portal:user_home' %}">
                    <img src=" {% static 'portal/assets/img/top_logo.png' %}" class="logo-icon" alt="logo icon">
                    <p class="logo-text"> NewsFeed</p>
                </a>
            </div>

            <ul class="sidebar-menu do-nicescrol">
                <li class="sidebar-header">User Portal</li>
                <li>
                    <a href="{% url 'portal:user_home' %}" class="waves-effect">
                        <i class="fa fa-tachometer"></i><span>Home</span>
                    </a>
                </li>
                <li>
                    <a href="javascript:;" class="waves-effect">
                        <i class="fa fa-bullhorn"></i><span>Readlist</span>
                        <i class="fa fa-angle-left float-right"></i>
                    </a>
                    <ul class="sidebar-submenu">
                        <li>
                            <a href="{% url 'portal:user_create_readlist' %}">
                                <i class="fa fa-circle-o"></i>
                                Create
                            </a>
                        </li>
                    </ul>
                    <ul class="sidebar-submenu">
                        <li>
                            <a href="{% url 'portal:user_manage_readlists' %}">
                                <i class="fa fa-circle-o"></i>
                                Manage
                            </a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="{% url 'global_home' %}" class="waves-effect">
                        <i class="fa fa-sign-out"></i><span>Sign out</span>
                    </a>
                </li>
            </ul>
        </div>
        <!--End sidebar-wrapper-->


        <!--Start topbar header-->
        <header class="topbar-nav">
            <nav class="navbar navbar-expand fixed-top" style="background:#fff">
                <ul class="navbar-nav my-nav align-items-center ">
                    <li class="nav-item">
                        <a class="nav-link toggle-menu" href="javascript:;">
                            <span class="icon-menu menu-icon">
                                <i class="fa fa-bars"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <li class="nav-item">
                    {% block search %}
                    <form
                        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
                        <div class="input-group mb-0 search_input_group mr-3">
                            <input class="form-control header_search" type="text" id="ad_search" name="q"
                                placeholder="Search" value="">
                        </div>
                    </form>
                    {% endblock %}
                </li>

                <ul class="navbar-nav align-items-center right-nav-link ml-auto">
                    <li class="nav-item">
                        <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown"
                            href="javascript:;">
                            <span class="user-profile">
                                <!-- <img src="{% static 'portal/assets/img/download.jpeg' %}" class="img-circle"
                                    alt="user avatar"> -->
                            </span>
                            <span style="font-size: 16px;color: #333;">{{user.username}}</span>
                            <i class="fa fa-angle-down" style="font-size: 16px;color: #000;"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-menu-right animated fadeIn">

                            <li class="dropdown-divider"></li>
                            <a href="{% url 'portal:user_profile_settings' %}">
                                <li class="dropdown-item"><i class="icon-power mr-2"></i> Profile </li>
                            </a>
                            <a href="{% url 'global_home' %}">
                                <li class="dropdown-item"><i class="icon-power mr-2"></i> Signout </li>
                            </a>
                        </ul>
                    </li>
                </ul>
            </nav>
        </header>
        <!--End topbar header-->
        <div class="clearfix"></div>

        <!--End wrapper-->

        <div class="content-wrapper">
            {% block content %}{% endblock %}
        </div>

        <!--Start Back To Top Button-->
        <a href="javascript:;" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
        <!--End Back To Top Button-->
    </div>
    <!-- Bootstrap Js -->
    <script src="{% static 'portal/assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'portal/assets/js/simplebar.js' %}"></script>
    <script src="{% static 'portal/assets/js/waves.js' %}"></script>
    <script src="{% static 'portal/assets/js/sidebar-menu.js' %}"></script>
    <script src="{% static 'portal/assets/js/slick.min.js' %}"></script>

    <!-- Datatables js -->
    <script language="JavaScript" src="{% static 'portal/assets/js/jquery.dataTables.min.js' %}"></script>
    <script language="JavaScript" src="{% static 'portal/assets/js/dataTables.bootstrap4.min.js' %}"></script>

    <!-- Custom JS -->
    <script src="{% static 'portal/assets/js/main.js' %}"></script>
    <script>
        $('#id_add_file').click(function (e) {
            var type = $('#id_ad_type').val();
            if (type == 'null') {
                e.preventDefault();
                $('#msg').text('Please Select Ad type First').fadeIn(500).delay(2000).fadeOut(500);
            }
        });

        $('#id_add_file').change(function () {

            var type = $('#id_ad_type').val();
            console.log(type);
            if (type == 'LS') {
                var fileInput = document.getElementById('id_add_file');
                var filePath = fileInput.value;
                console.log('file_path:--"' + filePath);
                var allowedExtensions = /(\.png|\.gif)$/i;

                //var size = fileInput.files[0].size/1024/1024 //size in MB

                var file = fileInput.files && fileInput.files[0];
                if (!allowedExtensions.exec(filePath)) {
                    console.log(fileInput.value);
                    fileInput.value = '';
                    //alert('Please upload Image having extensions .jpeg/.jpg/.png/.gif only');
                    $('#msg').text("Please Upload An Image Having Extensions .png/.PNG Only").fadeIn(1000)
                        .delay(3000).fadeOut(1000);
                    return false;
                }
            } else if (type == 'FS') {
                var fileInput = document.getElementById('id_add_file');
                var filePath = fileInput.value;
                console.log('file_path:--"' + filePath);
                var allowedExtensions = /(\.mp4)$/i;

                //var size = fileInput.files[0].size/1024/1024 //size in MB

                var file = fileInput.files && fileInput.files[0];
                if (!allowedExtensions.exec(filePath)) {
                    console.log(fileInput.value);
                    fileInput.value = '';
                    //alert('Please upload Video having extensions .jpeg/.jpg/.png/.gif only');
                    $('#msg').text("Please Upload A Video Having Extensions .mp4 Only").fadeIn(1000).delay(
                        3000).fadeOut(1000);
                    return false;
                }
            }
        })

        $('#id_ad_type').change(function () {
            var fileInput = document.getElementById('id_add_file');
            fileInput.value = '';
        })
    </script>

    {% block script %} {% endblock %}

    <style type="text/css">
        .loading_msg {
            position: absolute;
            background: #2d2d2d87;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #ffffff !important;
            z-index: 999;
        }

        .full_page_loading_msg {
            position: absolute;
            background: #2d2d2d87;
            width: 100%;
            height: 100%;
            display: flex;
            align-items: center;
            justify-content: center;
            color: #ffffff !important;
            z-index: 999;
        }

        .table-responsive {
            position: relative;
        }
    </style>
</body>

</html>